import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen max-h-screen flex flex-col`}>
                <nav className="shadow-[0_2px_8px_0_rgba(0,0,0,0.1)] z-50">
                    <div className="flex py-4 justify-between max-w-[1200px] w-[90%] m-auto">
                        <a href="/" className="font-bold text-2xl italic">
                            套件筆記
                        </a>
                        <a href="/blog">部落格</a>
                    </div>
                </nav>
                {children}
            </body>
        </html>
    );
}
